set(Qt6_FOUND TRUE)
set(QT_VERSION_MAJOR 6)
set(QT_VERSION 6.0.0)
set(Qt6_VERSION 6.0.0)

if(NOT COMMAND qt_add_executable)
function(qt_add_executable target)
    set(options MANUAL_FINALIZATION)
    cmake_parse_arguments(QT_EXE "${options}" "" "" ${ARGN})
    add_executable(${target} ${QT_EXE_UNPARSED_ARGUMENTS})
endfunction()
endif()

if(NOT COMMAND qt_finalize_executable)
function(qt_finalize_executable target)
endfunction()
endif()

if(NOT TARGET Qt6::moc)
    add_executable(Qt6::moc IMPORTED)
    set_target_properties(Qt6::moc PROPERTIES IMPORTED_LOCATION "/bin/true")
endif()
if(NOT TARGET Qt6::rcc)
    add_executable(Qt6::rcc IMPORTED)
    set_target_properties(Qt6::rcc PROPERTIES IMPORTED_LOCATION "/bin/true")
endif()
if(NOT TARGET Qt6::uic)
    add_executable(Qt6::uic IMPORTED)
    set_target_properties(Qt6::uic PROPERTIES IMPORTED_LOCATION "/bin/true")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/Qt6WidgetsConfig.cmake")
