name: Build

on:
  push:
  pull_request:

jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -S . -B build
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: windows
          target: desktop
          arch: win64_msvc2019_64
      - name: Configure CMake
        run: cmake -S . -B build -A x64 -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"
      - name: Build
        run: cmake --build build --config Release
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: DemulEASY-windows
          path: build/Release/DemulEASY.exe
